################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Defined Pipeline Stages
stages:
  - Contacts
  - Products
  - Orders
  - Invoices

################################################################
# Docker Init & Install Tests
################################################################

.docker:    &docker
    image:      docker:stable
    retry:      2
    tags:
      - Dedicated-Docker
    services:
      - docker:dind
    before_script:
      - sh ci/before_script.sh
    script:
      - sh ci/start_odoo.sh
      - sh ci/test_odoo.sh
    after_script:
      - sh ci/after_script.sh

################################################################
# Contacts - Functional Tests
################################################################

V12:Contacts:
  <<: *docker
  stage:              Contacts
  variables:
    PHPUNIT_CONFIG:   phpunit.contacts.xml
    ODOO_VERSION:     odoo:12

#V13:Contacts:
#  <<: *docker
#  stage:              Contacts
#  variables:
#    PHPUNIT_CONFIG:   phpunit.contacts.xml
#    ODOO_VERSION:     odoo:13
#
#V14:Contacts:
#  <<: *docker
#  stage:              Contacts
#  variables:
#    PHPUNIT_CONFIG:   phpunit.contacts.xml
#    ODOO_VERSION:     odoo:14
#
#V15:Contacts:
#  <<: *docker
#  stage:              Contacts
#  variables:
#    PHPUNIT_CONFIG:   phpunit.contacts.xml
#    ODOO_VERSION:     odoo:15

################################################################
# Products - Functional Tests
################################################################

V12:Products:
  <<: *docker
  stage:              Products
  variables:
    PHPUNIT_CONFIG:   phpunit.products.xml
    ODOO_VERSION:     odoo:12

#V13:Products:
#  <<: *docker
#  stage:              Products
#  variables:
#    PHPUNIT_CONFIG:   phpunit.products.xml
#    ODOO_VERSION:     odoo:13
#
#V14:Products:
#  <<: *docker
#  stage:              Products
#  variables:
#    PHPUNIT_CONFIG:   phpunit.products.xml
#    ODOO_VERSION:     odoo:14
#
#V15:Products:
#  <<: *docker
#  stage:              Products
#  variables:
#    PHPUNIT_CONFIG:   phpunit.products.xml
#    ODOO_VERSION:     odoo:15

################################################################
# Orders - Functional Tests
################################################################

V12:Orders:
  <<: *docker
  stage:              Orders
  variables:
    PHPUNIT_CONFIG:   phpunit.orders.xml
    ODOO_VERSION:     odoo:12

#V13:Orders:
#  <<: *docker
#  stage:              Orders
#  variables:
#    PHPUNIT_CONFIG:   phpunit.orders.xml
#    ODOO_VERSION:     odoo:13
#
#V14:Orders:
#  <<: *docker
#  stage:              Orders
#  variables:
#    PHPUNIT_CONFIG:   phpunit.orders.xml
#    ODOO_VERSION:     odoo:14
#
#V15:Orders:
#  <<: *docker
#  stage:              Orders
#  variables:
#    PHPUNIT_CONFIG:   phpunit.orders.xml
#    ODOO_VERSION:     odoo:15

################################################################
# Invoices - Functional Tests
################################################################

#V12:Invoices:
#  <<: *docker
#  stage:              Invoices
#  variables:
#    PHPUNIT_CONFIG:   phpunit.invoices.xml
#    ODOO_VERSION:     odoo:12
#
#V13:Invoices:
#  <<: *docker
#  stage:              Invoices
#  variables:
#    PHPUNIT_CONFIG:   phpunit.invoices.xml
#    ODOO_VERSION:     odoo:13
#
#V14:Invoices:
#  <<: *docker
#  stage:              Invoices
#  variables:
#    PHPUNIT_CONFIG:   phpunit.invoices.xml
#    ODOO_VERSION:     odoo:14
#
#V15:Invoices:
#  <<: *docker
#  stage:              Invoices
#  variables:
#    PHPUNIT_CONFIG:   phpunit.invoices.xml
#    ODOO_VERSION:     odoo:15

################################################################
# Build Documentation
################################################################
pages:
    image:      registry.gitlab.com/splashsync/php-console:pages
    stage:      deploy
    retry:      2
    tags:
      - Dedicated
    ################################################################################
    # Run Test Script
    script:
      # Run Composer to Build Dependencies
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
      # Build Documentation
      - php vendor/bin/grumphp run --tasks=build-docs
    artifacts:
        paths:
            - public