################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
################################################################################

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

################################################################
# Defined Pipeline Stages
stages:
#  - Docker
  - Contacts
  - Products
  - Orders
  - Invoices
  - Deploy

################################################################
# Init & Functional Tests
################################################################

.functional:    &functional
    image:      docker/compose
    when:       manual
    retry:      1
    tags:
      - Dedicated-Docker
    services:
      - docker:dind
    artifacts:
        name: "$CI_JOB_NAME"
        when: always
        paths:
            - logs
    before_script:
      - sh ci/before_script.sh
    script:
      - sh ci/start_odoo.sh
      - sh ci/test_odoo.sh
    after_script:
      - sh ci/after_script.sh


################################################################
# Contacts - Functional Tests
################################################################

# ALL TESTS PASSED
V12:Contacts:
    <<: *functional
    stage:              Contacts
    variables:          { ODOO_VERSION:     12, PHPUNIT_CONFIG:   phpunit.contacts.xml }
#  when:               always

V13:Contacts:
    <<: *functional
    stage:              Contacts
    variables:          { ODOO_VERSION:     13, PHPUNIT_CONFIG:   phpunit.contacts.xml }
#  when:               always

V14:Contacts:
    <<: *functional
    stage:              Contacts
    variables:          { ODOO_VERSION:     14, PHPUNIT_CONFIG:   phpunit.contacts.xml }
#  when:               always

V15:Contacts:
    <<: *functional
    stage:              Contacts
    variables:          { ODOO_VERSION:     15, PHPUNIT_CONFIG:   phpunit.contacts.xml }
#  when:               always

#################################################################
## Products - Functional Tests
#################################################################

V12:Products:
    <<: *functional
    stage:              Products
    variables:          { ODOO_VERSION:     12, PHPUNIT_CONFIG:   phpunit.products.xml }
#  when:               always

V13:Products:
    <<: *functional
    stage:              Products
    variables:          { ODOO_VERSION:     13, PHPUNIT_CONFIG:   phpunit.products.xml }
#  when:               always

V14:Products:
    <<: *functional
    stage:              Products
    variables:          { ODOO_VERSION:     14, PHPUNIT_CONFIG:   phpunit.products.xml }
#    when:               always

V15:Products:
    <<: *functional
    stage:              Products
    variables:          { ODOO_VERSION:     15, PHPUNIT_CONFIG:   phpunit.products.xml }
#    when:               always

#################################################################
## Orders - Functional Tests
#################################################################

V12:Orders:
    <<: *functional
    stage:              Orders
    variables:          { ODOO_VERSION:     12, PHPUNIT_CONFIG:   phpunit.orders.xml }
#    when:               always

V13:Orders:
    <<: *functional
    stage:              Orders
    variables:          { ODOO_VERSION:     13, PHPUNIT_CONFIG:   phpunit.orders.xml }
#    when:               always

V14:Orders:
    <<: *functional
    stage:              Orders
    variables:          { ODOO_VERSION:     14, PHPUNIT_CONFIG:   phpunit.orders.xml }
#    when:               always

V15:Orders:
    <<: *functional
    stage:              Orders
    variables:          { ODOO_VERSION:     15, PHPUNIT_CONFIG:   phpunit.orders.xml }
#    when:               always

#################################################################
## Invoices - Functional Tests
#################################################################

V12:Invoices:
    <<: *functional
    stage:              Invoices
    variables:          { ODOO_VERSION:     12, PHPUNIT_CONFIG:   phpunit.invoices.xml }
    when:               always

V13:Invoices:
    <<: *functional
    stage:              Invoices
    variables:          { ODOO_VERSION:     13, PHPUNIT_CONFIG:   phpunit.invoices.xml }
    when:               always

V14:Invoices:
    <<: *functional
    stage:              Invoices
    variables:          { ODOO_VERSION:     14, PHPUNIT_CONFIG:   phpunit.invoices.xml }
    when:               always

V15:Invoices:
    <<: *functional
    stage:              Invoices
    variables:          { ODOO_VERSION:     15, PHPUNIT_CONFIG:   phpunit.invoices.xml }
    when:               always

################################################################
# Build Documentation
################################################################
pages:
    image:      registry.gitlab.com/splashsync/php-console:pages
    stage:      Deploy
    retry:      2
    tags:
      - Dedicated
    ################################################################################
    # Run Test Script
    script:
      # Run Composer to Build Dependencies
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
      # Build Documentation
      - php vendor/bin/grumphp run --tasks=build-docs
    artifacts:
        paths:
            - public