################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync  <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Dev Environment
# for Splash Modules
#
# 172.120.0.99        latest.odoo.local
# 172.120.0.12        v12.odoo.local
# 172.120.0.13        v13.odoo.local
# 172.120.0.14        v14.odoo.local
# 172.120.0.15        v15.odoo.local
# 172.120.0.16        v16.odoo.local
# 172.120.0.17        v17.odoo.local
# 172.120.0.100       toolkit.odoo.local
# 172.120.0.101       db.odoo.local
#
################################################################################

version: "3.2"

services:

    ################################################################################
    # Odoo V16 Server Container
    odoo-16:
        image:  odoo:16
        container_name: v16.odoo.local
        depends_on:
            - db
        volumes:
            - ./resources/docker/odoo:/etc/odoo:ro
            - ./splashsync:/mnt/extra-addons/splashsync:ro
        entrypoint:         bash /etc/odoo/entrypoint.sh
        hostname:           v16.odoo.local
        networks:
            odoo:           { ipv4_address: 172.120.0.16, aliases: [ v16.odoo.local ] }
            splashsync:     { aliases: [ v16.odoo.local ] }
        env_file:
            - ./resources/docker/odoo/odoo.env
        environment:
            - ODOO_DATABASE=OdooV16
            - ODOO_INTERFACE=172.120.0.16
            - ODOO_DEV=1

    ################################################################################
    # Postgres Database Container
    db:
        image: postgres:12
        container_name: db.odoo.local
#        logging: { driver: "none" }
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
        hostname:           db.odoo.local
        networks:
            odoo:           { ipv4_address: 172.120.0.101, aliases: [ db.odoo.local ] }

    ################################################################################
    # Splash Toolkit Container
    toolkit:
        image:          'splashsync/toolkit'
        container_name: toolkit.odoo.local
        logging:        { driver: "none" }
        volumes:
            # Specify Local Tests
            - './resources/docker/toolkit/tests:/app/tests:ro'
            # Specify Local Configuration File
            - './resources/docker/toolkit/splash.yaml:/app/config/packages/splash.yaml:ro'
            - './resources/docker/toolkit/phpunit.products.xml:/app/phpunit.products.xml:ro'
            - './resources/docker/toolkit/phpunit.contacts.xml:/app/phpunit.contacts.xml:ro'
            - './resources/docker/toolkit/phpunit.invoices.xml:/app/phpunit.invoices.xml:ro'
            - './resources/docker/toolkit/phpunit.orders.xml:/app/phpunit.orders.xml:ro'
        hostname:           toolkit.odoo.local
        networks:
            odoo:           { ipv4_address: 172.120.0.100, aliases: [ toolkit.odoo.local ] }
            splashsync:     { aliases: [ toolkit.odoo.local ] }

networks:
    ################################################################################
    # Default Private Network
    odoo:
        driver: bridge
        ipam:
            config:
                - subnet: 172.120.0.0/24
    ################################################################################
    # External Splash Network
    splashsync:
        external: true