#
#  This file is part of SplashSync Project.
#
#  Copyright (C) 2015-2020 Splash Sync  <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Dev Environment
# for Splash Modules
#
# 172.120.0.99        latest.odoo.local
# 172.120.0.100       toolkit.odoo.local
#
################################################################################

version: "3.2"

services:

    ################################################################################
    # Odoo Server Container
    odoo:
        image:  odoo:12
        container_name: odoo-latest
        depends_on:
            - db
        ports:
            - "8069:8069"
        volumes:
            - ./docker/x86:/etc/odoo:ro
            - ./odoo/addons/splashsync:/mnt/extra-addons/splashsync:ro
            - ../Py-Core:/mnt/splashpy
#        entrypoint:         bash /etc/odoo/entrypoint.sh odoo -i "splashsync,product,contacts,stock,website_sale_comparison,sales,purchase"
        entrypoint:         bash /etc/odoo/entrypoint.sh odoo -i "splashsync"
#        entrypoint:         bash /etc/odoo/entrypoint.sh odoo
        hostname:           latest.odoo.local
        networks:
            odoo:           { ipv4_address: 172.120.0.99, aliases: [ latest.odoo.local ] }
            splashsync:     { aliases: [ latest.odoo.local ] }

    ################################################################################
    # Postgres Database Container
    db:
        image: postgres:10
        container_name: odoo-db
        logging: { driver: "none" }
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
        hostname:           db.odoo.local
        networks:
            odoo:           { ipv4_address: 172.120.0.101, aliases: [ db.odoo.local ] }

    ################################################################################
    # Splash Toolkit Container
    toolkit:
        image: 'splashsync/toolkit'
        container_name: odoo-toolkit
        logging: { driver: "none" }
        volumes:
            # Specify Local Configuration File
            - './docker/toolkit/splash.yml:/app/config/packages/splash.yml:ro'
        hostname:           toolkit.odoo.local
        networks:
            odoo:           { ipv4_address: 172.120.0.100, aliases: [ toolkit.odoo.local ] }
            splashsync:     { aliases: [ toolkit.odoo.local ] }

networks:
    ################################################################################
    # Default Private Network
    odoo:
        driver: bridge
        ipam:
            config:
                - subnet: 172.120.0.0/24
    ################################################################################
    # External Splash Network
    splashsync:
        external: true