################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync  <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
################################################################################

name:   "splashsync_odoo_${ODOO_VERSION}_env"

################################################################################
# Developer Odoo Docker Compose Stack
services:
    ################################################################################
    # Odoo Debug Container
    dev:
        image:          "odoo:${ODOO_VERSION}"
        container_name: dev.odoo.local
        depends_on:
            - db
            - toolkit
        volumes:
            - ./resources/docker/odoo:/etc/odoo:ro
            - ./splashsync:/mnt/extra-addons/splashsync:ro
        entrypoint:         bash /etc/odoo/entrypoint.sh
        hostname:           dev.odoo.local
        networks:
            odoo:           { ipv4_address: 172.120.0.11, aliases: [ dev.odoo.local ] }
            splashsync:     { aliases: [ dev.odoo.local ] }
        env_file:
            - ./resources/docker/odoo/odoo.env
        environment:
            - ODOO_DATABASE=Odoo${ODOO_VERSION}Dev
            - ODOO_INTERFACE=172.120.0.11
            - ODOO_DEV=1

################################################################################
# Generic Odoo Docker Compose Stack
include:
  - ./resources/docker/docker-compose.yaml
