################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync  <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Dev Environment
# for Splash Modules
#
# 172.120.0.99        latest.odoo.local
# 172.120.0.12        v12.odoo.local
# 172.120.0.13        v13.odoo.local
# 172.120.0.14        v14.odoo.local
# 172.120.0.15        v15.odoo.local
# 172.120.0.16        v16.odoo.local
# 172.120.0.17        v17.odoo.local
# 172.120.0.100       toolkit.odoo.local
# 172.120.0.101       db.odoo.local
#
################################################################################

version: "3.2"

services:

    ################################################################################
    # Odoo DEV Server Container
    odoo:
        image:  odoo:13
        container_name: latest.odoo.local
        depends_on:
            - db
        volumes:
            - ./docker/odoo:/etc/odoo:ro
            - ./odoo/addons/splashsync:/mnt/extra-addons/splashsync:ro
            - ./scripts:/scripts:ro
            - ../Py-Core:/mnt/splashpy
        entrypoint:         bash /etc/odoo/entrypoint.sh
        hostname:           latest.odoo.local
        networks:
            odoo:           { ipv4_address: 172.120.0.99, aliases: [ latest.odoo.local ] }
            splashsync:     { aliases: [ latest.odoo.local ] }
        env_file:
            - docker/odoo/odoo.env
        environment:
            - ODOO_DATABASE=OdooLatest
            - ODOO_INTERFACE=172.120.0.99
            - ODOO_DEV=1

    ################################################################################
    # Odoo V16 Server Container
    odoo-16:
        image:  odoo:16
        container_name: v16.odoo.local
        depends_on:
            - db
        volumes:
            - ./docker/odoo:/etc/odoo:ro
            - ./odoo/addons/splashsync:/mnt/extra-addons/splashsync:ro
        entrypoint:         bash /etc/odoo/entrypoint.sh
        hostname:           v16.odoo.local
        networks:
            odoo:           { ipv4_address: 172.120.0.16, aliases: [ v16.odoo.local ] }
            splashsync:     { aliases: [ v16.odoo.local ] }
        env_file:
            - docker/odoo/odoo.env
        environment:
            - ODOO_DATABASE=OdooV16
            - ODOO_INTERFACE=172.120.0.16
            - ODOO_DEV=1

    ################################################################################
    # Odoo V15 Server Container
    odoo-15:
        image:  odoo:15
        container_name: v15.odoo.local
        depends_on:
            - db
        volumes:
            - ./docker/odoo:/etc/odoo:ro
            - ./odoo/addons/splashsync:/mnt/extra-addons/splashsync:ro
        entrypoint:         bash /etc/odoo/entrypoint.sh
        hostname:           v15.odoo.local
        networks:
            odoo:           { ipv4_address: 172.120.0.15, aliases: [ v15.odoo.local ] }
            splashsync:     { aliases: [ v15.odoo.local ] }
        env_file:
            - docker/odoo/odoo.env
        environment:
            - ODOO_DATABASE=OdooV15
            - ODOO_INTERFACE=172.120.0.15
            - ODOO_DEV=1

    ################################################################################
    # Odoo V14 Server Container
    odoo-14:
        image:  odoo:14
        container_name: v14.odoo.local
        depends_on:
            - db
        volumes:
            - ./docker/odoo:/etc/odoo:ro
            - ./odoo/addons/splashsync:/mnt/extra-addons/splashsync:ro
            - ../Py-Core:/mnt/splashpy
        entrypoint:         bash /etc/odoo/entrypoint.sh
        hostname:           v14.odoo.local
        networks:
            odoo:           { ipv4_address: 172.120.0.14, aliases: [ v14.odoo.local ] }
            splashsync:     { aliases: [ v14.odoo.local ] }
        env_file:
            - docker/odoo/odoo.env
        environment:
            - ODOO_DATABASE=OdooV14
            - ODOO_INTERFACE=172.120.0.14
            - ODOO_DEV=1

    ################################################################################
    # Odoo V13 Server Container
    odoo-13:
        image:  odoo:13
        container_name: v13.odoo.local
        depends_on:
            - db
        volumes:
            - ./docker/odoo:/etc/odoo:ro
            - ./odoo/addons/splashsync:/mnt/extra-addons/splashsync:ro
            - ../Py-Core:/mnt/splashpy
        entrypoint:         bash /etc/odoo/entrypoint.sh
        hostname:           v13.odoo.local
        networks:
            odoo:           { ipv4_address: 172.120.0.13, aliases: [ v13.odoo.local ] }
            splashsync:     { aliases: [ v13.odoo.local ] }
        env_file:
            - docker/odoo/odoo.env
        environment:
            - ODOO_DATABASE=OdooV13
            - ODOO_INTERFACE=172.120.0.13
            - ODOO_DEV=1

    ################################################################################
    # Odoo V12 Server Container
    odoo-12:
        image:  odoo:12
        container_name: v12.odoo.local
        depends_on:
            - db
        volumes:
            - ./docker/odoo:/etc/odoo:ro
            - ./odoo/addons/splashsync:/mnt/extra-addons/splashsync:ro
            - ../Py-Core:/mnt/splashpy
        entrypoint:         bash /etc/odoo/entrypoint.sh
        hostname:           v12.odoo.local
        networks:
            odoo:           { ipv4_address: 172.120.0.12, aliases: [ v12.odoo.local ] }
            splashsync:     { aliases: [ v12.odoo.local ] }
        env_file:
            - docker/odoo/odoo.env
        environment:
            - ODOO_DATABASE=OdooV12
            - ODOO_INTERFACE=172.120.0.12
            - ODOO_DEV=1

    ################################################################################
    # Postgres Database Container
    db:
        image: postgres:12
        container_name: db.odoo.local
#        logging: { driver: "none" }
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
        hostname:           db.odoo.local
        networks:
            odoo:           { ipv4_address: 172.120.0.101, aliases: [ db.odoo.local ] }

    ################################################################################
    # Splash Toolkit Container
    toolkit:
        image: 'splashsync/toolkit:alpine'
        container_name: toolkit.odoo.local
        logging: { driver: "none" }
        volumes:
            # Specify Local Tests
            - './docker/toolkit/tests:/app/tests:ro'
            # Specify Local Configuration File
#            - './docker/toolkit/splash.yml:/app/config/packages/splash.yml:ro'
            - './docker/toolkit/splash-dev.yml:/app/config/packages/splash.yaml:ro'
            - './docker/toolkit/phpunit.products.xml:/app/phpunit.products.xml:ro'
            - './docker/toolkit/phpunit.contacts.xml:/app/phpunit.contacts.xml:ro'
            - './docker/toolkit/phpunit.invoices.xml:/app/phpunit.invoices.xml:ro'
            - './docker/toolkit/phpunit.orders.xml:/app/phpunit.orders.xml:ro'
        hostname:           toolkit.odoo.local
        networks:
            odoo:           { ipv4_address: 172.120.0.100, aliases: [ toolkit.odoo.local ] }
            splashsync:     { aliases: [ toolkit.odoo.local ] }

networks:
    ################################################################################
    # Default Private Network
    odoo:
        driver: bridge
        ipam:
            config:
                - subnet: 172.120.0.0/24
    ################################################################################
    # External Splash Network
    splashsync:
        external: true