################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
################################################################################

variables:
  DOCKER_HOST:              tcp://docker:2375/
  DOCKER_DRIVER:            overlay2
  GIT_SUBMODULE_STRATEGY:   normal

################################################################
# Defined Pipeline Stages
stages:
  - Contacts
  - Products
  - Orders
  - Invoices
#  - deploy

################################################################
# Init & Functional Tests
################################################################

.functional:    &functional
    image:      docker:latest
    tags:
      - Dedicated-Docker
    services:
      - docker:dind
    artifacts:
        name: "$CI_JOB_NAME"
        when: always
        paths:
            - logs
            - manifest
            - reports
        reports:
            junit: "*-report.xml"
    before_script:
      - sh resources/ci/before_script.sh
    script:
      - sh resources/ci/start_odoo.sh
      - sh resources/ci/test_odoo.sh
    after_script:
      - sh resources/ci/after_script.sh

################################################################
# Contacts - Functional Tests
################################################################

Contacts:C0-Main:
    <<: *functional
    stage:              Contacts
    variables:
        SPLASH_SEQUENCE:  "Odoo Main"
        SPLASH_TYPES:     "Address,ThirdParty"
    when:               always

Contacts:C1-Extra:
    <<: *functional
    stage:              Contacts
    needs:              ["Contacts:C0-Main"]
    variables:
        SPLASH_SEQUENCE:  "Odoo C1"
        SPLASH_TYPES:     "Address,ThirdParty"
    when:               always

Contacts:C2-Extra:
    <<: *functional
    stage:              Contacts
    needs:              ["Contacts:C0-Main"]
    variables:
        SPLASH_SEQUENCE:  "Odoo C2"
        SPLASH_TYPES:     "Address,ThirdParty"
    when:               always

################################################################
# Products - Functional Tests
################################################################

Products:C0-Main:
    <<: *functional
    stage:                Products
    variables:
        SPLASH_SEQUENCE:  "Odoo Main"
        SPLASH_TYPES:     "Product"
    when:                 always

Products:C1-Extra:
    <<: *functional
    stage:                Products
    needs:                ["Products:C0-Main"]
    variables:
        SPLASH_SEQUENCE:  "Odoo C1"
        SPLASH_TYPES:     "Product"
    when:                 always

Products:C2-Extra:
    <<: *functional
    stage:                Products
    needs:                ["Products:C0-Main"]
    variables:
        SPLASH_SEQUENCE:  "Odoo C2"
        SPLASH_TYPES:     "Product"
    when:                 always

#################################################################
## Orders - Functional Tests
#################################################################

Orders:C0-Main:
    <<: *functional
    stage:                Orders
    variables:
        SPLASH_SEQUENCE:  "Odoo Main"
        SPLASH_TYPES:     "Order"
    when:                 always

Orders:C1-Extra:
    <<: *functional
    stage:                Orders
    needs:                ["Orders:C0-Main"]
    variables:
        SPLASH_SEQUENCE:  "Odoo C1"
        SPLASH_TYPES:     "Order"
    when:                 manual

Orders:C2-Extra:
    <<: *functional
    stage:                Orders
    variables:
        SPLASH_SEQUENCE:  "Odoo C2"
        SPLASH_TYPES:     "Order"
    when:                 manual

################################################################
# Invoices - Functional Tests
################################################################

Invoices:C0-Main:
    <<: *functional
    stage:                Invoices
    variables:
        SPLASH_SEQUENCE:  "Odoo Main"
        SPLASH_TYPES:     "Invoice"
    when:                 always

Invoices:C1-Extra:
    <<: *functional
    stage:                Invoices
    needs:                ["Invoices:C0-Main"]
    variables:
        SPLASH_SEQUENCE:  "Odoo C1"
        SPLASH_TYPES:     "Invoice"
    when:                 manual

Invoices:C2-Extra:
    <<: *functional
    stage:                Invoices
    needs:                ["Invoices:C0-Main"]
    variables:
        SPLASH_SEQUENCE:  "Odoo C2"
        SPLASH_TYPES:     "Invoice"
    when:                 manual
