################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync  <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a CI/CD Environment
# for Splash Modules Testing
#
# 172.120.0.99        latest.odoo.local
# 172.120.0.100       toolkit.odoo.local
# 172.120.0.101       db.odoo.local
#
################################################################################

version: "3.2"

services:

    ################################################################################
    # Odoo Server Container
    odoo:
        image:  odoo:latest
        container_name: latest.odoo.local
        depends_on:
            - db
        volumes:
            - ./docker/odoo:/etc/odoo:ro
            - ./odoo/addons/splashsync:/mnt/extra-addons/splashsync:ro
            - ./scripts:/scripts:ro
        entrypoint:         bash /etc/odoo/entrypoint.sh
        hostname:           latest.odoo.local
        environment:
            - ODOO_DATABASE=OdooLatest
            - ODOO_MODULES=contacts,product,website_sale_comparison,sale,purchase,stock,point_of_sale
            - CI_MODE=enabled
            - ODOO_LOG_LEVEL=":INFO"

    ################################################################################
    # Postgres Database Container
    db:
        image: postgres:10
        container_name: db.odoo.local
        logging: { driver: "none" }
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
        hostname:           db.odoo.local

    ################################################################################
    # Splash Toolkit Container
    toolkit:
        image: 'splashsync/toolkit'
        container_name: toolkit.odoo.local
        logging: { driver: "none" }
        volumes:
            # Specify Local Configuration File
            - './ci/splash.yml:/app/config/packages/splash.yml:ro'
            - './docker/toolkit/phpunit.products.xml:/app/phpunit.products.xml:ro'
            - './docker/toolkit/phpunit.contacts.xml:/app/phpunit.contacts.xml:ro'
            - './docker/toolkit/phpunit.invoices.xml:/app/phpunit.invoices.xml:ro'
            - './docker/toolkit/phpunit.orders.xml:/app/phpunit.orders.xml:ro'
        hostname:           toolkit.odoo.local

